spring:
    mvc:
        view:
            suffix: .html
            prefix: /
        static-path-pattern: /**
    web:
        # config web resources
        resources:
            static-locations: classpath:/templates/, classpath:/static/, classpath:/resources/, classpath:/public/
    # unset cache
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
    # config database
    datasource:
        username: xosmos
        password: xosmos010502
        url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=True&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
# use MyBatis
mybatis:
    type-aliases-package: com.xosmos.entity
    mapper-locations: classpath:mybatis/mapper/*.xml
    config-location: classpath:mybatis-config.xml


